name: 📚 Documentation Issue
description: Report an issue with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: Which documentation are you referring to?
      options:
        - README.md
        - API.md (API Documentation)
        - DEPLOYMENT.md (Deployment Guide)
        - CONTRIBUTING.md (Contributing Guide)
        - SECURITY.md (Security Policy)
        - CODE_OF_CONDUCT.md
        - Code Comments
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing Information
        - Incorrect Information
        - Outdated Information
        - Unclear/Confusing
        - Typo/Grammar
        - Formatting Issue
        - Broken Link
        - Needs Example
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where specifically is the issue? (file name, section, line number)
      placeholder: |
        File: README.md
        Section: Installation
        Line: 45
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (copy/paste if possible)
      placeholder: Currently, it says...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: What should it say instead? How can we improve it?
      placeholder: It should say... or It would be clearer if...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Why is this change important? Who would benefit?
      placeholder: This would help users understand...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR to fix this documentation issue

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked that this issue hasn't already been reported
          required: true
