name: ✨ Feature Request
description: Suggest a new feature or enhancement for Valiant Picks
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? If so, describe it.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I also thought about...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - User Experience
        - Betting System
        - Admin Tools
        - Analytics/Statistics
        - Notifications
        - Social Features
        - Performance
        - Security
        - Mobile App
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking usage)
        - High (Would significantly improve experience)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature benefit users?
      placeholder: |
        - Saves time by...
        - Makes it easier to...
        - Improves user engagement by...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be used
      placeholder: |
        1. As a user, I want to...
        2. As an admin, I need to...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have any mockups, screenshots, or examples from other apps, share them here
      placeholder: Drag and drop images or paste links...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have technical suggestions for implementation, share them here
      placeholder: This could be implemented by...

  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      description: Would you be willing to help?
      options:
        - label: I would be willing to contribute code for this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to write documentation for this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature would benefit the general user base (not just me)
          required: true
